# Generated by Django 3.0.4 on 2021-10-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='itemb',
        ),
    ]
