# Generated by Django 4.0.5 on 2022-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='amount',
            new_name='commission',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='item',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.AddField(
            model_name='service',
            name='added_by',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
