# Generated by Django 4.0.5 on 2022-08-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_amount_service_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='added_by',
            new_name='addedby',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='added_on',
            new_name='addedon',
        ),
    ]
