# Generated by Django 4.0.5 on 2022-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_added_by_service_addedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('addedby', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=1, max_length=1)),
                ('addedon', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
