# Generated by Django 4.0.5 on 2022-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_employees_employee_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
