# Generated by Django 4.0.5 on 2022-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_orderdetail_delete_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='staff',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
