# Generated by Django 4.0.5 on 2022-08-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderdetail_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
    ]
