# Generated by Django 4.0.5 on 2022-08-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_orderdetail_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
