# Generated by Django 4.0.5 on 2022-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_balance_employee_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=0, max_length=1000)),
                ('addedby', models.CharField(default=0, max_length=100)),
                ('status', models.CharField(default=1, max_length=1)),
                ('addedon', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
